import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
import { showModal, hideModal, resetNotification, disableError } from '../../Actions';
import { ADMIN_PAID_INFO } from '../../constants';
import style from './style.scss';

import Modal from './../Modal';
import Notification from '../SendArticleNotification';
import Donate from './../Donate';

class Header extends Component{
    constructor() {
        super();
        this.state = {
            _donate: false,
            _article: false,
        };
        this._adminPaidInfo = ADMIN_PAID_INFO;
    }

    modal = (modalType) => {
        const { modal } = this.props.headerState;
        if (modalType === 'donate') {
            switch (this.state._donate) {
                case false:
                    if (!modal.modal) {  // modal is CLOSED
                        this.setState({
                            _donate: true,
                        });
                        this.refs.donate.textContent = 'Закрыть';
                    }
                    break;
                case true:
                    this.setState({
                        _donate: false,
                    });
                    this.refs.donate.textContent = 'Донат';
                    break;
                default:
                    break;
            }
        }
        if (modalType === 'article') {
            switch (modal.modal) {
                case false: // modal is OPEN
                    this.props.showModal();
                    this.props.resetNotification();

                    this.setState({
                        _donate: false,
                    });
                    this.refs.donate.textContent = 'Донат';

                    break;
                case true: // modal is CLOSED
                    this.props.hideModal();
                    this.props.disableError();
                    break;
                default:
                    break;
            }
        }
    };

    render () {
        const { modal, notification } = this.props.headerState;
        return(
            <div className={"custom-container"}>
                <div id={'fixed-header'}>
                    <div className={"container custom-container__background"}>
                        <div className={"row"}>
                            <div className="col-md-3">
                                <div className="custom-container__donate">
                                    <button onClick={() => {::this.modal('donate')}} ref={'donate'}>Донат</button>
                                    {this.state._donate && <Donate paidInfo={this._adminPaidInfo}/>}
                                </div>
                            </div>
                            <div className="col-md-6">
                                <div className="custom-container__logotype">
                                    <img src={require('../../../images/frontside_studio.png')} width={100}/>
                                </div>
                            </div>
                            <div className="col-md-3">
                                <div className="custom-container__new-article">
                                    <button onClick={() => {::this.modal('article')}} ref={'article'}>{modal.modal ? 'Закрыть' : '+ Новая статья'}</button>
                                    {modal.modal && <Modal/>}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={"custom-container posts-container"}>
                    <div className={"container"}>
                        <div className={"row"}>
                            {notification.notificationInfo !== '' && <Notification/>}
                            <h1>Some posts...</h1>
                            <p>Celiac plaid four dollar toast kale chips aesthetic echo park before they sold out ugh. Food truck pinterest banjo, freegan unicorn health goth cardigan photo booth affogato pop-up roof party fanny pack wolf. Vape jean shorts gentrify disrupt umami echo park edison bulb VHS raclette, prism blue bottle la croix everyday carry asymmetrical. Vice prism raclette gochujang keffiyeh. Unicorn 8-bit chicharrones, cloud bread shoreditch viral ugh pinterest. Aesthetic before they sold out raclette mumblecore pug hot chicken echo park whatever vape succulents tilde slow-carb. Raw denim schlitz fanny pack asymmetrical disrupt. Blog mustache direct trade gochujang bushwick four dollar toast kombucha quinoa plaid subway tile. Af 8-bit post-ironic, butcher flannel gochujang man braid bicycle rights franzen. Shoreditch glossier schlitz, ethical chillwave unicorn craft beer sriracha tumblr cliche. Direct trade ethical readymade kitsch food truck migas 90's, snackwave quinoa hella shoreditch edison bulb. Scenester listicle tacos cred hammock, master cleanse narwhal intelligentsia neutra cloud bread. Kickstarter knausgaard direct trade swag cornhole palo santo, DIY cold-pressed celiac salvia literally. Stumptown marfa taxidermy brunch microdosing copper mug tbh asymmetrical banh mi retro chia selvage four dollar toast activated charcoal.

                                Twee air plant small batch vaporware godard pug. Blog taxidermy chambray shaman celiac polaroid. Beard irony church-key, portland fingerstache fanny pack tumblr. Quinoa hashtag stumptown mlkshk. Chicharrones ugh pug jianbing fam intelligentsia. Trust fund knausgaard meh skateboard slow-carb. Literally la croix mustache celiac hella adaptogen vape kitsch scenester. Cliche lumbersexual poutine, gentrify paleo polaroid before they sold out beard roof party YOLO shoreditch microdosing ethical. Twee hammock palo santo keffiyeh listicle truffaut. Thundercats bicycle rights synth tumblr meh. Freegan literally messenger bag, you probably haven't heard of them enamel pin beard fixie tousled readymade ugh tofu blue bottle flexitarian meggings.

                                 unicorn fanny pack roof party occupy heirloom leggings shabby chic cardigan tilde flannel. Lo-fi listicle sustainable, migas kinfolk XOXO truffaut. Edison bulb banjo copper mug sriracha affogato readymade YOLO taiyaki organic forage DIY truffaut sustainable viral lo-fi. Asymmetrical freegan ugh XOXO. Offal organic fam prism. Williamsburg activated charcoal man braid, letterpress etsy tumblr tote bag health goth brooklyn woke +1 bicycle rights. Hexagon chambray irony, roof party kombucha slow-carb raw denim artisan. Lo-fi +1 small batch pug bespoke banh mi try-hard hammock fam. Woke kitsch helvetica sustainable pickled, organic marfa actually lyft.

                                Adaptogen freegan aesthetic salvia pinterest. Fashion axe gastropub forage PBR&B wolf sustainable air plant DIY authentic fam shabby chic, pok pok humblebrag. Vape portland semiotics, lyft chillwave vice edison bulb umami glossier health goth mumblecore dreamcatcher la croix meditation kitsch. Subway tile prism lyft, fanny pack vice beard raw denim coloring book air plant. Pinterest air plant vegan organic. Edison bulb +1 next level blog taxidermy chambray artisan deep v portland distillery kombucha biodiesel helvetica health goth. Poke pickled semiotics ennui sriracha la croix. Hot chicken tumblr 90's bitters, plaid cronut deep v pop-up kombucha. Heirloom kickstarter knausgaard af, synth adaptogen roof party palo santo tbh whatever.

                                Succulents disrupt drinking vinegar knausgaard lo-fi. Intelligentsia bushwick selfies, aesthetic woke next level butcher health goth meditation small batch enamel pin. Distillery hexagon swag flexitarian ethical, woke polaroid franzen beard butcher taxidermy quinoa la croix. Palo santo polaroid synth meditation typewriter snackwave poke tacos meh vice. Etsy intelligentsia swag XOXO trust fund semiotics cloud bread thundercats fashion axe humblebrag. Keffiyeh blog cronut tumeric health goth iceland helvetica biodiesel plaid try-hard. Asymmetrical vegan ethical narwhal 3 wolf moon aesthetic. Sartorial fanny pack paleo, lumbersexual palo santo shabby chic poutine street art truffaut next level subway tile banh mi vaporware. Meh pinterest freegan artisan, kombucha scenester sriracha blue bottle woke gentrify direct trade. Pickled godard helvetica air plant lumbersexual cliche tousled seitan art party tilde vegan pour-over quinoa biodiesel. Prism meggings blog bespoke franzen cold-pressed.

                                Helvetica flexitarian craft beer tbh heirloom iPhone yr. Kombucha dreamcatcher pour-over schlitz iceland retro before they sold out live-edge marfa master cleanse neutra ramps shabby chic. Brunch man bun banh mi paleo distillery. Helvetica typewriter vexillologist selvage williamsburg ethical. Pabst thundercats sustainable celiac. Unicorn forage photo booth poutine roof party franzen. Migas squid plaid cronut hot chicken letterpress tumblr schlitz. Beard plaid sriracha pok pok vinyl. Edison bulb artisan pok pok brooklyn normcore celiac. Sustainable direct trade twee, biodiesel irony post-ironic master cleanse sartorial blue bottle bespoke thundercats bushwick. Lomo microdosing asymmetrical, church-key sriracha flexitarian food truck before they sold out iceland air plant vape biodiesel vice messenger bag cornhole.

                                Occupy vinyl helvetica church-key small batch, glossier squid. Organic celiac shaman, whatever keytar skateboard next level paleo green juice bushwick. Drinking vinegar poke poutine, tumblr food truck 8-bit forage seitan XOXO. Tacos leggings asymmetrical helvetica occupy butcher master cleanse, readymade forage. Four loko chartreuse letterpress vape master cleanse YOLO. Single-origin coffee small batch lo-fi, vape palo santo stumptown gochujang hella kombucha wayfarers. Shabby chic thundercats vinyl cloud bread quinoa taiyaki banh mi, waistcoat artisan af enamel pin before they sold out viral knausgaard cred. Kickstarter offal pok pok cardigan live-edge la croix flexitarian kombucha pickled mixtape cred locavore thundercats. Bushwick tousled disrupt meh lo-fi pok pok VHS succulents gentrify shoreditch lyft aesthetic mixtape YOLO asymmetrical. Farm-to-table chillwave ennui, mlkshk activated charcoal retro semiotics whatever blue bottle literally fixie. Kickstarter scenester poutine wayfarers farm-to-table +1. Fashion axe shabby chic polaroid air plant single-origin coffee poke microdosing pug hell of cliche schlitz activated charcoal glossier pitchfork four loko. Sriracha 90's chicharrones iceland typewriter. Helvetica direct trade chartreuse sustainable cliche, portland pug intelligentsia farm-to-table.

                                Lyft lomo narwhal cardigan gochujang godard austin kinfolk paleo. Ethical fingerstache iceland fashion axe. Hexagon neutra shoreditch tilde pok pok asymmetrical la croix 8-bit umami kogi. Schlitz occupy kitsch taxidermy freegan. Knausgaard lo-fi 90's, tumeric portland raw denim gluten-free. Pickled adaptogen next level normcore. Snackwave fanny pack microdosing tilde readymade distillery single-origin coffee offal kickstarter hexagon. Vinyl prism pork belly ethical, blue bottle freegan biodiesel quinoa. Thundercats viral subway tile, cornhole tote bag portland fashion axe lo-fi migas. Banh mi cred shoreditch yuccie four dollar toast coloring book air plant pork belly, chicharrones etsy 3 wolf moon. Quinoa banjo shaman master cleanse gentrify chicharrones.

                                90's intelligentsia blue bottle pitchfork post-ironic, la croix vexillologist. Adaptogen thundercats pitchfork, hammock knausgaard man bun bicycle rights VHS synth kombucha kogi pok pok. Mixtape photo booth cloud bread, helvetica hell of swag bitters vexillologist brooklyn marfa iPhone literally humblebrag vegan. Banh mi echo park bespoke gastropub, four dollar toast +1 glossier freegan vinyl retro thundercats wayfarers. Hexagon raclette direct trade tacos. Meggings intelligentsia tumblr, chillwave chambray glossier poke adaptogen enamel pin church-key paleo hella woke small batch. Keytar cloud bread raclette, keffiyeh ramps hell of put a bird on it tousled deep v locavore mustache skateboard vape pickled DIY. Fam neutra edison bulb ramps intelligentsia. Fanny pack etsy cred typewriter shoreditch enamel pin listicle hashtag art party stumptown put a bird on it salvia hexagon tattooed subway tile. Tattooed tumblr letterpress, tote bag shaman hashtag brunch. Affogato umami four loko bespoke retro kitsch chartreuse banh mi hell of. Chicharrones chia microdosing irony, tilde sartorial you probably haven't heard of them coloring book authentic succulents green juice cloud bread cardigan taiyaki adaptogen. Butcher hell of organic trust fund, adaptogen lo-fi ennui. Health goth +1 actually, vexillologist wolf banh mi before they sold out taxidermy twee intelligentsia. Celiac truffaut master cleanse small batch disrupt tacos cardigan bushwick microdosing succulents you probably haven't heard of them sriracha portland church-key VHS.

                                Neutra hell of mixtape live-edge dreamcatcher cornhole helvetica. Freegan VHS organic tote bag, franzen affogato subway tile synth schlitz succulents pok pok kombucha iceland enamel pin umami. Beard forage pork belly synth kickstarter, street art kinfolk. Shabby chic keytar narwhal fixie jianbing poutine vice. Af vegan health goth street art letterpress cardigan, hella gluten-free copper mug man bun heirloom meditation dreamcatcher. Cornhole adaptogen ugh deep v franzen. Forage PBR&B before they sold out vaporware, locavore food truck hoodie neutra disrupt cronut. Fam tilde cray, ennui humblebrag meh marfa ethical meditation. Pinterest seitan master cleanse drinking vinegar fingerstache, hexagon cray PBR&B jianbing street art. Shabby chic 90's asymmetrical literally polaroid. PBR&B heirloom food truck kogi franzen. Organic hashtag pickled fixie semiotics vinyl stumptown tousled af cray subway tile sriracha intelligentsia actually master cleanse.

                                Lumbersexual vexillologist meggings neutra shabby chic schlitz bushwick four loko pickled pop-up. Street art retro copper mug raclette cloud bread drinking vinegar lomo pop-up health goth fashion axe art party. Shaman glossier vaporware thundercats jean shorts gochujang meh vice franzen bicycle rights tofu artisan tacos. Chicharrones vape hot chicken chartreuse cliche small batch. Enamel pin you probably haven't heard of them meh taiyaki pickled selfies meditation flexitarian. La croix pok pok cold-pressed, lo-fi tofu farm-to-table normcore deep v chillwave kitsch try-hard. Trust fund cardigan scenester, succulents jianbing XOXO lomo meh literally live-edge pabst typewriter. Echo park fam sriracha small batch live-edge venmo everyday carry drinking vinegar neutra biodiesel pitchfork 8-bit lyft kombucha. Actually art party stumptown coloring book raw denim narwhal.

                                Swag flannel 3 wolf moon.</p><hr/>
                            <p>Celiac plaid four dollar toast kale chips aesthetic echo park before they sold out ugh. Food truck pinterest banjo, freegan unicorn health goth cardigan photo booth affogato pop-up roof party fanny pack wolf. Vape jean shorts gentrify disrupt umami echo park edison bulb VHS raclette, prism blue bottle la croix everyday carry asymmetrical. Vice prism raclette gochujang keffiyeh. Unicorn 8-bit chicharrones, cloud bread shoreditch viral ugh pinterest. Aesthetic before they sold out raclette mumblecore pug hot chicken echo park whatever vape succulents tilde slow-carb. Raw denim schlitz fanny pack asymmetrical disrupt. Blog mustache direct trade gochujang bushwick four dollar toast kombucha quinoa plaid subway tile. Af 8-bit post-ironic, butcher flannel gochujang man braid bicycle rights franzen. Shoreditch glossier schlitz, ethical chillwave unicorn craft beer sriracha tumblr cliche. Direct trade ethical readymade kitsch food truck migas 90's, snackwave quinoa hella shoreditch edison bulb. Scenester listicle tacos cred hammock, master cleanse narwhal intelligentsia neutra cloud bread. Kickstarter knausgaard direct trade swag cornhole palo santo, DIY cold-pressed celiac salvia literally. Stumptown marfa taxidermy brunch microdosing copper mug tbh asymmetrical banh mi retro chia selvage four dollar toast activated charcoal.

                                Twee air plant small batch vaporware godard pug. Blog taxidermy chambray shaman celiac polaroid. Beard irony church-key, portland fingerstache fanny pack tumblr. Quinoa hashtag stumptown mlkshk. Chicharrones ugh pug jianbing fam intelligentsia. Trust fund knausgaard meh skateboard slow-carb. Literally la croix mustache celiac hella adaptogen vape kitsch scenester. Cliche lumbersexual poutine, gentrify paleo polaroid before they sold out beard roof party YOLO shoreditch microdosing ethical. Twee hammock palo santo keffiyeh listicle truffaut. Thundercats bicycle rights synth tumblr meh. Freegan literally messenger bag, you probably haven't heard of them enamel pin beard fixie tousled readymade ugh tofu blue bottle flexitarian meggings.

                                unicorn fanny pack roof party occupy heirloom leggings shabby chic cardigan tilde flannel. Lo-fi listicle sustainable, migas kinfolk XOXO truffaut. Edison bulb banjo copper mug sriracha affogato readymade YOLO taiyaki organic forage DIY truffaut sustainable viral lo-fi. Asymmetrical freegan ugh XOXO. Offal organic fam prism. Williamsburg activated charcoal man braid, letterpress etsy tumblr tote bag health goth brooklyn woke +1 bicycle rights. Hexagon chambray irony, roof party kombucha slow-carb raw denim artisan. Lo-fi +1 small batch pug bespoke banh mi try-hard hammock fam. Woke kitsch helvetica sustainable pickled, organic marfa actually lyft.

                                Adaptogen freegan aesthetic salvia pinterest. Fashion axe gastropub forage PBR&B wolf sustainable air plant DIY authentic fam shabby chic, pok pok humblebrag. Vape portland semiotics, lyft chillwave vice edison bulb umami glossier health goth mumblecore dreamcatcher la croix meditation kitsch. Subway tile prism lyft, fanny pack vice beard raw denim coloring book air plant. Pinterest air plant vegan organic. Edison bulb +1 next level blog taxidermy chambray artisan deep v portland distillery kombucha biodiesel helvetica health goth. Poke pickled semiotics ennui sriracha la croix. Hot chicken tumblr 90's bitters, plaid cronut deep v pop-up kombucha. Heirloom kickstarter knausgaard af, synth adaptogen roof party palo santo tbh whatever.

                                Succulents disrupt drinking vinegar knausgaard lo-fi. Intelligentsia bushwick selfies, aesthetic woke next level butcher health goth meditation small batch enamel pin. Distillery hexagon swag flexitarian ethical, woke polaroid franzen beard butcher taxidermy quinoa la croix. Palo santo polaroid synth meditation typewriter snackwave poke tacos meh vice. Etsy intelligentsia swag XOXO trust fund semiotics cloud bread thundercats fashion axe humblebrag. Keffiyeh blog cronut tumeric health goth iceland helvetica biodiesel plaid try-hard. Asymmetrical vegan ethical narwhal 3 wolf moon aesthetic. Sartorial fanny pack paleo, lumbersexual palo santo shabby chic poutine street art truffaut next level subway tile banh mi vaporware. Meh pinterest freegan artisan, kombucha scenester sriracha blue bottle woke gentrify direct trade. Pickled godard helvetica air plant lumbersexual cliche tousled seitan art party tilde vegan pour-over quinoa biodiesel. Prism meggings blog bespoke franzen cold-pressed.

                                Helvetica flexitarian craft beer tbh heirloom iPhone yr. Kombucha dreamcatcher pour-over schlitz iceland retro before they sold out live-edge marfa master cleanse neutra ramps shabby chic. Brunch man bun banh mi paleo distillery. Helvetica typewriter vexillologist selvage williamsburg ethical. Pabst thundercats sustainable celiac. Unicorn forage photo booth poutine roof party franzen. Migas squid plaid cronut hot chicken letterpress tumblr schlitz. Beard plaid sriracha pok pok vinyl. Edison bulb artisan pok pok brooklyn normcore celiac. Sustainable direct trade twee, biodiesel irony post-ironic master cleanse sartorial blue bottle bespoke thundercats bushwick. Lomo microdosing asymmetrical, church-key sriracha flexitarian food truck before they sold out iceland air plant vape biodiesel vice messenger bag cornhole.

                                Occupy vinyl helvetica church-key small batch, glossier squid. Organic celiac shaman, whatever keytar skateboard next level paleo green juice bushwick. Drinking vinegar poke poutine, tumblr food truck 8-bit forage seitan XOXO. Tacos leggings asymmetrical helvetica occupy butcher master cleanse, readymade forage. Four loko chartreuse letterpress vape master cleanse YOLO. Single-origin coffee small batch lo-fi, vape palo santo stumptown gochujang hella kombucha wayfarers. Shabby chic thundercats vinyl cloud bread quinoa taiyaki banh mi, waistcoat artisan af enamel pin before they sold out viral knausgaard cred. Kickstarter offal pok pok cardigan live-edge la croix flexitarian kombucha pickled mixtape cred locavore thundercats. Bushwick tousled disrupt meh lo-fi pok pok VHS succulents gentrify shoreditch lyft aesthetic mixtape YOLO asymmetrical. Farm-to-table chillwave ennui, mlkshk activated charcoal retro semiotics whatever blue bottle literally fixie. Kickstarter scenester poutine wayfarers farm-to-table +1. Fashion axe shabby chic polaroid air plant single-origin coffee poke microdosing pug hell of cliche schlitz activated charcoal glossier pitchfork four loko. Sriracha 90's chicharrones iceland typewriter. Helvetica direct trade chartreuse sustainable cliche, portland pug intelligentsia farm-to-table.

                                Lyft lomo narwhal cardigan gochujang godard austin kinfolk paleo. Ethical fingerstache iceland fashion axe. Hexagon neutra shoreditch tilde pok pok asymmetrical la croix 8-bit umami kogi. Schlitz occupy kitsch taxidermy freegan. Knausgaard lo-fi 90's, tumeric portland raw denim gluten-free. Pickled adaptogen next level normcore. Snackwave fanny pack microdosing tilde readymade distillery single-origin coffee offal kickstarter hexagon. Vinyl prism pork belly ethical, blue bottle freegan biodiesel quinoa. Thundercats viral subway tile, cornhole tote bag portland fashion axe lo-fi migas. Banh mi cred shoreditch yuccie four dollar toast coloring book air plant pork belly, chicharrones etsy 3 wolf moon. Quinoa banjo shaman master cleanse gentrify chicharrones.

                                90's intelligentsia blue bottle pitchfork post-ironic, la croix vexillologist. Adaptogen thundercats pitchfork, hammock knausgaard man bun bicycle rights VHS synth kombucha kogi pok pok. Mixtape photo booth cloud bread, helvetica hell of swag bitters vexillologist brooklyn marfa iPhone literally humblebrag vegan. Banh mi echo park bespoke gastropub, four dollar toast +1 glossier freegan vinyl retro thundercats wayfarers. Hexagon raclette direct trade tacos. Meggings intelligentsia tumblr, chillwave chambray glossier poke adaptogen enamel pin church-key paleo hella woke small batch. Keytar cloud bread raclette, keffiyeh ramps hell of put a bird on it tousled deep v locavore mustache skateboard vape pickled DIY. Fam neutra edison bulb ramps intelligentsia. Fanny pack etsy cred typewriter shoreditch enamel pin listicle hashtag art party stumptown put a bird on it salvia hexagon tattooed subway tile. Tattooed tumblr letterpress, tote bag shaman hashtag brunch. Affogato umami four loko bespoke retro kitsch chartreuse banh mi hell of. Chicharrones chia microdosing irony, tilde sartorial you probably haven't heard of them coloring book authentic succulents green juice cloud bread cardigan taiyaki adaptogen. Butcher hell of organic trust fund, adaptogen lo-fi ennui. Health goth +1 actually, vexillologist wolf banh mi before they sold out taxidermy twee intelligentsia. Celiac truffaut master cleanse small batch disrupt tacos cardigan bushwick microdosing succulents you probably haven't heard of them sriracha portland church-key VHS.

                                Neutra hell of mixtape live-edge dreamcatcher cornhole helvetica. Freegan VHS organic tote bag, franzen affogato subway tile synth schlitz succulents pok pok kombucha iceland enamel pin umami. Beard forage pork belly synth kickstarter, street art kinfolk. Shabby chic keytar narwhal fixie jianbing poutine vice. Af vegan health goth street art letterpress cardigan, hella gluten-free copper mug man bun heirloom meditation dreamcatcher. Cornhole adaptogen ugh deep v franzen. Forage PBR&B before they sold out vaporware, locavore food truck hoodie neutra disrupt cronut. Fam tilde cray, ennui humblebrag meh marfa ethical meditation. Pinterest seitan master cleanse drinking vinegar fingerstache, hexagon cray PBR&B jianbing street art. Shabby chic 90's asymmetrical literally polaroid. PBR&B heirloom food truck kogi franzen. Organic hashtag pickled fixie semiotics vinyl stumptown tousled af cray subway tile sriracha intelligentsia actually master cleanse.

                                Lumbersexual vexillologist meggings neutra shabby chic schlitz bushwick four loko pickled pop-up. Street art retro copper mug raclette cloud bread drinking vinegar lomo pop-up health goth fashion axe art party. Shaman glossier vaporware thundercats jean shorts gochujang meh vice franzen bicycle rights tofu artisan tacos. Chicharrones vape hot chicken chartreuse cliche small batch. Enamel pin you probably haven't heard of them meh taiyaki pickled selfies meditation flexitarian. La croix pok pok cold-pressed, lo-fi tofu farm-to-table normcore deep v chillwave kitsch try-hard. Trust fund cardigan scenester, succulents jianbing XOXO lomo meh literally live-edge pabst typewriter. Echo park fam sriracha small batch live-edge venmo everyday carry drinking vinegar neutra biodiesel pitchfork 8-bit lyft kombucha. Actually art party stumptown coloring book raw denim narwhal.

                                Swag flannel 3 wolf moon.</p><hr/>
                            <p>Celiac plaid four dollar toast kale chips aesthetic echo park before they sold out ugh. Food truck pinterest banjo, freegan unicorn health goth cardigan photo booth affogato pop-up roof party fanny pack wolf. Vape jean shorts gentrify disrupt umami echo park edison bulb VHS raclette, prism blue bottle la croix everyday carry asymmetrical. Vice prism raclette gochujang keffiyeh. Unicorn 8-bit chicharrones, cloud bread shoreditch viral ugh pinterest. Aesthetic before they sold out raclette mumblecore pug hot chicken echo park whatever vape succulents tilde slow-carb. Raw denim schlitz fanny pack asymmetrical disrupt. Blog mustache direct trade gochujang bushwick four dollar toast kombucha quinoa plaid subway tile. Af 8-bit post-ironic, butcher flannel gochujang man braid bicycle rights franzen. Shoreditch glossier schlitz, ethical chillwave unicorn craft beer sriracha tumblr cliche. Direct trade ethical readymade kitsch food truck migas 90's, snackwave quinoa hella shoreditch edison bulb. Scenester listicle tacos cred hammock, master cleanse narwhal intelligentsia neutra cloud bread. Kickstarter knausgaard direct trade swag cornhole palo santo, DIY cold-pressed celiac salvia literally. Stumptown marfa taxidermy brunch microdosing copper mug tbh asymmetrical banh mi retro chia selvage four dollar toast activated charcoal.

                                Twee air plant small batch vaporware godard pug. Blog taxidermy chambray shaman celiac polaroid. Beard irony church-key, portland fingerstache fanny pack tumblr. Quinoa hashtag stumptown mlkshk. Chicharrones ugh pug jianbing fam intelligentsia. Trust fund knausgaard meh skateboard slow-carb. Literally la croix mustache celiac hella adaptogen vape kitsch scenester. Cliche lumbersexual poutine, gentrify paleo polaroid before they sold out beard roof party YOLO shoreditch microdosing ethical. Twee hammock palo santo keffiyeh listicle truffaut. Thundercats bicycle rights synth tumblr meh. Freegan literally messenger bag, you probably haven't heard of them enamel pin beard fixie tousled readymade ugh tofu blue bottle flexitarian meggings.

                                unicorn fanny pack roof party occupy heirloom leggings shabby chic cardigan tilde flannel. Lo-fi listicle sustainable, migas kinfolk XOXO truffaut. Edison bulb banjo copper mug sriracha affogato readymade YOLO taiyaki organic forage DIY truffaut sustainable viral lo-fi. Asymmetrical freegan ugh XOXO. Offal organic fam prism. Williamsburg activated charcoal man braid, letterpress etsy tumblr tote bag health goth brooklyn woke +1 bicycle rights. Hexagon chambray irony, roof party kombucha slow-carb raw denim artisan. Lo-fi +1 small batch pug bespoke banh mi try-hard hammock fam. Woke kitsch helvetica sustainable pickled, organic marfa actually lyft.

                                Adaptogen freegan aesthetic salvia pinterest. Fashion axe gastropub forage PBR&B wolf sustainable air plant DIY authentic fam shabby chic, pok pok humblebrag. Vape portland semiotics, lyft chillwave vice edison bulb umami glossier health goth mumblecore dreamcatcher la croix meditation kitsch. Subway tile prism lyft, fanny pack vice beard raw denim coloring book air plant. Pinterest air plant vegan organic. Edison bulb +1 next level blog taxidermy chambray artisan deep v portland distillery kombucha biodiesel helvetica health goth. Poke pickled semiotics ennui sriracha la croix. Hot chicken tumblr 90's bitters, plaid cronut deep v pop-up kombucha. Heirloom kickstarter knausgaard af, synth adaptogen roof party palo santo tbh whatever.

                                Succulents disrupt drinking vinegar knausgaard lo-fi. Intelligentsia bushwick selfies, aesthetic woke next level butcher health goth meditation small batch enamel pin. Distillery hexagon swag flexitarian ethical, woke polaroid franzen beard butcher taxidermy quinoa la croix. Palo santo polaroid synth meditation typewriter snackwave poke tacos meh vice. Etsy intelligentsia swag XOXO trust fund semiotics cloud bread thundercats fashion axe humblebrag. Keffiyeh blog cronut tumeric health goth iceland helvetica biodiesel plaid try-hard. Asymmetrical vegan ethical narwhal 3 wolf moon aesthetic. Sartorial fanny pack paleo, lumbersexual palo santo shabby chic poutine street art truffaut next level subway tile banh mi vaporware. Meh pinterest freegan artisan, kombucha scenester sriracha blue bottle woke gentrify direct trade. Pickled godard helvetica air plant lumbersexual cliche tousled seitan art party tilde vegan pour-over quinoa biodiesel. Prism meggings blog bespoke franzen cold-pressed.

                                Helvetica flexitarian craft beer tbh heirloom iPhone yr. Kombucha dreamcatcher pour-over schlitz iceland retro before they sold out live-edge marfa master cleanse neutra ramps shabby chic. Brunch man bun banh mi paleo distillery. Helvetica typewriter vexillologist selvage williamsburg ethical. Pabst thundercats sustainable celiac. Unicorn forage photo booth poutine roof party franzen. Migas squid plaid cronut hot chicken letterpress tumblr schlitz. Beard plaid sriracha pok pok vinyl. Edison bulb artisan pok pok brooklyn normcore celiac. Sustainable direct trade twee, biodiesel irony post-ironic master cleanse sartorial blue bottle bespoke thundercats bushwick. Lomo microdosing asymmetrical, church-key sriracha flexitarian food truck before they sold out iceland air plant vape biodiesel vice messenger bag cornhole.

                                Occupy vinyl helvetica church-key small batch, glossier squid. Organic celiac shaman, whatever keytar skateboard next level paleo green juice bushwick. Drinking vinegar poke poutine, tumblr food truck 8-bit forage seitan XOXO. Tacos leggings asymmetrical helvetica occupy butcher master cleanse, readymade forage. Four loko chartreuse letterpress vape master cleanse YOLO. Single-origin coffee small batch lo-fi, vape palo santo stumptown gochujang hella kombucha wayfarers. Shabby chic thundercats vinyl cloud bread quinoa taiyaki banh mi, waistcoat artisan af enamel pin before they sold out viral knausgaard cred. Kickstarter offal pok pok cardigan live-edge la croix flexitarian kombucha pickled mixtape cred locavore thundercats. Bushwick tousled disrupt meh lo-fi pok pok VHS succulents gentrify shoreditch lyft aesthetic mixtape YOLO asymmetrical. Farm-to-table chillwave ennui, mlkshk activated charcoal retro semiotics whatever blue bottle literally fixie. Kickstarter scenester poutine wayfarers farm-to-table +1. Fashion axe shabby chic polaroid air plant single-origin coffee poke microdosing pug hell of cliche schlitz activated charcoal glossier pitchfork four loko. Sriracha 90's chicharrones iceland typewriter. Helvetica direct trade chartreuse sustainable cliche, portland pug intelligentsia farm-to-table.

                                Lyft lomo narwhal cardigan gochujang godard austin kinfolk paleo. Ethical fingerstache iceland fashion axe. Hexagon neutra shoreditch tilde pok pok asymmetrical la croix 8-bit umami kogi. Schlitz occupy kitsch taxidermy freegan. Knausgaard lo-fi 90's, tumeric portland raw denim gluten-free. Pickled adaptogen next level normcore. Snackwave fanny pack microdosing tilde readymade distillery single-origin coffee offal kickstarter hexagon. Vinyl prism pork belly ethical, blue bottle freegan biodiesel quinoa. Thundercats viral subway tile, cornhole tote bag portland fashion axe lo-fi migas. Banh mi cred shoreditch yuccie four dollar toast coloring book air plant pork belly, chicharrones etsy 3 wolf moon. Quinoa banjo shaman master cleanse gentrify chicharrones.

                                90's intelligentsia blue bottle pitchfork post-ironic, la croix vexillologist. Adaptogen thundercats pitchfork, hammock knausgaard man bun bicycle rights VHS synth kombucha kogi pok pok. Mixtape photo booth cloud bread, helvetica hell of swag bitters vexillologist brooklyn marfa iPhone literally humblebrag vegan. Banh mi echo park bespoke gastropub, four dollar toast +1 glossier freegan vinyl retro thundercats wayfarers. Hexagon raclette direct trade tacos. Meggings intelligentsia tumblr, chillwave chambray glossier poke adaptogen enamel pin church-key paleo hella woke small batch. Keytar cloud bread raclette, keffiyeh ramps hell of put a bird on it tousled deep v locavore mustache skateboard vape pickled DIY. Fam neutra edison bulb ramps intelligentsia. Fanny pack etsy cred typewriter shoreditch enamel pin listicle hashtag art party stumptown put a bird on it salvia hexagon tattooed subway tile. Tattooed tumblr letterpress, tote bag shaman hashtag brunch. Affogato umami four loko bespoke retro kitsch chartreuse banh mi hell of. Chicharrones chia microdosing irony, tilde sartorial you probably haven't heard of them coloring book authentic succulents green juice cloud bread cardigan taiyaki adaptogen. Butcher hell of organic trust fund, adaptogen lo-fi ennui. Health goth +1 actually, vexillologist wolf banh mi before they sold out taxidermy twee intelligentsia. Celiac truffaut master cleanse small batch disrupt tacos cardigan bushwick microdosing succulents you probably haven't heard of them sriracha portland church-key VHS.

                                Neutra hell of mixtape live-edge dreamcatcher cornhole helvetica. Freegan VHS organic tote bag, franzen affogato subway tile synth schlitz succulents pok pok kombucha iceland enamel pin umami. Beard forage pork belly synth kickstarter, street art kinfolk. Shabby chic keytar narwhal fixie jianbing poutine vice. Af vegan health goth street art letterpress cardigan, hella gluten-free copper mug man bun heirloom meditation dreamcatcher. Cornhole adaptogen ugh deep v franzen. Forage PBR&B before they sold out vaporware, locavore food truck hoodie neutra disrupt cronut. Fam tilde cray, ennui humblebrag meh marfa ethical meditation. Pinterest seitan master cleanse drinking vinegar fingerstache, hexagon cray PBR&B jianbing street art. Shabby chic 90's asymmetrical literally polaroid. PBR&B heirloom food truck kogi franzen. Organic hashtag pickled fixie semiotics vinyl stumptown tousled af cray subway tile sriracha intelligentsia actually master cleanse.

                                Lumbersexual vexillologist meggings neutra shabby chic schlitz bushwick four loko pickled pop-up. Street art retro copper mug raclette cloud bread drinking vinegar lomo pop-up health goth fashion axe art party. Shaman glossier vaporware thundercats jean shorts gochujang meh vice franzen bicycle rights tofu artisan tacos. Chicharrones vape hot chicken chartreuse cliche small batch. Enamel pin you probably haven't heard of them meh taiyaki pickled selfies meditation flexitarian. La croix pok pok cold-pressed, lo-fi tofu farm-to-table normcore deep v chillwave kitsch try-hard. Trust fund cardigan scenester, succulents jianbing XOXO lomo meh literally live-edge pabst typewriter. Echo park fam sriracha small batch live-edge venmo everyday carry drinking vinegar neutra biodiesel pitchfork 8-bit lyft kombucha. Actually art party stumptown coloring book raw denim narwhal.

                                Swag flannel 3 wolf moon.</p><hr/>
                            <p>Celiac plaid four dollar toast kale chips aesthetic echo park before they sold out ugh. Food truck pinterest banjo, freegan unicorn health goth cardigan photo booth affogato pop-up roof party fanny pack wolf. Vape jean shorts gentrify disrupt umami echo park edison bulb VHS raclette, prism blue bottle la croix everyday carry asymmetrical. Vice prism raclette gochujang keffiyeh. Unicorn 8-bit chicharrones, cloud bread shoreditch viral ugh pinterest. Aesthetic before they sold out raclette mumblecore pug hot chicken echo park whatever vape succulents tilde slow-carb. Raw denim schlitz fanny pack asymmetrical disrupt. Blog mustache direct trade gochujang bushwick four dollar toast kombucha quinoa plaid subway tile. Af 8-bit post-ironic, butcher flannel gochujang man braid bicycle rights franzen. Shoreditch glossier schlitz, ethical chillwave unicorn craft beer sriracha tumblr cliche. Direct trade ethical readymade kitsch food truck migas 90's, snackwave quinoa hella shoreditch edison bulb. Scenester listicle tacos cred hammock, master cleanse narwhal intelligentsia neutra cloud bread. Kickstarter knausgaard direct trade swag cornhole palo santo, DIY cold-pressed celiac salvia literally. Stumptown marfa taxidermy brunch microdosing copper mug tbh asymmetrical banh mi retro chia selvage four dollar toast activated charcoal.

                                Twee air plant small batch vaporware godard pug. Blog taxidermy chambray shaman celiac polaroid. Beard irony church-key, portland fingerstache fanny pack tumblr. Quinoa hashtag stumptown mlkshk. Chicharrones ugh pug jianbing fam intelligentsia. Trust fund knausgaard meh skateboard slow-carb. Literally la croix mustache celiac hella adaptogen vape kitsch scenester. Cliche lumbersexual poutine, gentrify paleo polaroid before they sold out beard roof party YOLO shoreditch microdosing ethical. Twee hammock palo santo keffiyeh listicle truffaut. Thundercats bicycle rights synth tumblr meh. Freegan literally messenger bag, you probably haven't heard of them enamel pin beard fixie tousled readymade ugh tofu blue bottle flexitarian meggings.

                                unicorn fanny pack roof party occupy heirloom leggings shabby chic cardigan tilde flannel. Lo-fi listicle sustainable, migas kinfolk XOXO truffaut. Edison bulb banjo copper mug sriracha affogato readymade YOLO taiyaki organic forage DIY truffaut sustainable viral lo-fi. Asymmetrical freegan ugh XOXO. Offal organic fam prism. Williamsburg activated charcoal man braid, letterpress etsy tumblr tote bag health goth brooklyn woke +1 bicycle rights. Hexagon chambray irony, roof party kombucha slow-carb raw denim artisan. Lo-fi +1 small batch pug bespoke banh mi try-hard hammock fam. Woke kitsch helvetica sustainable pickled, organic marfa actually lyft.

                                Adaptogen freegan aesthetic salvia pinterest. Fashion axe gastropub forage PBR&B wolf sustainable air plant DIY authentic fam shabby chic, pok pok humblebrag. Vape portland semiotics, lyft chillwave vice edison bulb umami glossier health goth mumblecore dreamcatcher la croix meditation kitsch. Subway tile prism lyft, fanny pack vice beard raw denim coloring book air plant. Pinterest air plant vegan organic. Edison bulb +1 next level blog taxidermy chambray artisan deep v portland distillery kombucha biodiesel helvetica health goth. Poke pickled semiotics ennui sriracha la croix. Hot chicken tumblr 90's bitters, plaid cronut deep v pop-up kombucha. Heirloom kickstarter knausgaard af, synth adaptogen roof party palo santo tbh whatever.

                                Succulents disrupt drinking vinegar knausgaard lo-fi. Intelligentsia bushwick selfies, aesthetic woke next level butcher health goth meditation small batch enamel pin. Distillery hexagon swag flexitarian ethical, woke polaroid franzen beard butcher taxidermy quinoa la croix. Palo santo polaroid synth meditation typewriter snackwave poke tacos meh vice. Etsy intelligentsia swag XOXO trust fund semiotics cloud bread thundercats fashion axe humblebrag. Keffiyeh blog cronut tumeric health goth iceland helvetica biodiesel plaid try-hard. Asymmetrical vegan ethical narwhal 3 wolf moon aesthetic. Sartorial fanny pack paleo, lumbersexual palo santo shabby chic poutine street art truffaut next level subway tile banh mi vaporware. Meh pinterest freegan artisan, kombucha scenester sriracha blue bottle woke gentrify direct trade. Pickled godard helvetica air plant lumbersexual cliche tousled seitan art party tilde vegan pour-over quinoa biodiesel. Prism meggings blog bespoke franzen cold-pressed.

                                Helvetica flexitarian craft beer tbh heirloom iPhone yr. Kombucha dreamcatcher pour-over schlitz iceland retro before they sold out live-edge marfa master cleanse neutra ramps shabby chic. Brunch man bun banh mi paleo distillery. Helvetica typewriter vexillologist selvage williamsburg ethical. Pabst thundercats sustainable celiac. Unicorn forage photo booth poutine roof party franzen. Migas squid plaid cronut hot chicken letterpress tumblr schlitz. Beard plaid sriracha pok pok vinyl. Edison bulb artisan pok pok brooklyn normcore celiac. Sustainable direct trade twee, biodiesel irony post-ironic master cleanse sartorial blue bottle bespoke thundercats bushwick. Lomo microdosing asymmetrical, church-key sriracha flexitarian food truck before they sold out iceland air plant vape biodiesel vice messenger bag cornhole.

                                Occupy vinyl helvetica church-key small batch, glossier squid. Organic celiac shaman, whatever keytar skateboard next level paleo green juice bushwick. Drinking vinegar poke poutine, tumblr food truck 8-bit forage seitan XOXO. Tacos leggings asymmetrical helvetica occupy butcher master cleanse, readymade forage. Four loko chartreuse letterpress vape master cleanse YOLO. Single-origin coffee small batch lo-fi, vape palo santo stumptown gochujang hella kombucha wayfarers. Shabby chic thundercats vinyl cloud bread quinoa taiyaki banh mi, waistcoat artisan af enamel pin before they sold out viral knausgaard cred. Kickstarter offal pok pok cardigan live-edge la croix flexitarian kombucha pickled mixtape cred locavore thundercats. Bushwick tousled disrupt meh lo-fi pok pok VHS succulents gentrify shoreditch lyft aesthetic mixtape YOLO asymmetrical. Farm-to-table chillwave ennui, mlkshk activated charcoal retro semiotics whatever blue bottle literally fixie. Kickstarter scenester poutine wayfarers farm-to-table +1. Fashion axe shabby chic polaroid air plant single-origin coffee poke microdosing pug hell of cliche schlitz activated charcoal glossier pitchfork four loko. Sriracha 90's chicharrones iceland typewriter. Helvetica direct trade chartreuse sustainable cliche, portland pug intelligentsia farm-to-table.

                                Lyft lomo narwhal cardigan gochujang godard austin kinfolk paleo. Ethical fingerstache iceland fashion axe. Hexagon neutra shoreditch tilde pok pok asymmetrical la croix 8-bit umami kogi. Schlitz occupy kitsch taxidermy freegan. Knausgaard lo-fi 90's, tumeric portland raw denim gluten-free. Pickled adaptogen next level normcore. Snackwave fanny pack microdosing tilde readymade distillery single-origin coffee offal kickstarter hexagon. Vinyl prism pork belly ethical, blue bottle freegan biodiesel quinoa. Thundercats viral subway tile, cornhole tote bag portland fashion axe lo-fi migas. Banh mi cred shoreditch yuccie four dollar toast coloring book air plant pork belly, chicharrones etsy 3 wolf moon. Quinoa banjo shaman master cleanse gentrify chicharrones.

                                90's intelligentsia blue bottle pitchfork post-ironic, la croix vexillologist. Adaptogen thundercats pitchfork, hammock knausgaard man bun bicycle rights VHS synth kombucha kogi pok pok. Mixtape photo booth cloud bread, helvetica hell of swag bitters vexillologist brooklyn marfa iPhone literally humblebrag vegan. Banh mi echo park bespoke gastropub, four dollar toast +1 glossier freegan vinyl retro thundercats wayfarers. Hexagon raclette direct trade tacos. Meggings intelligentsia tumblr, chillwave chambray glossier poke adaptogen enamel pin church-key paleo hella woke small batch. Keytar cloud bread raclette, keffiyeh ramps hell of put a bird on it tousled deep v locavore mustache skateboard vape pickled DIY. Fam neutra edison bulb ramps intelligentsia. Fanny pack etsy cred typewriter shoreditch enamel pin listicle hashtag art party stumptown put a bird on it salvia hexagon tattooed subway tile. Tattooed tumblr letterpress, tote bag shaman hashtag brunch. Affogato umami four loko bespoke retro kitsch chartreuse banh mi hell of. Chicharrones chia microdosing irony, tilde sartorial you probably haven't heard of them coloring book authentic succulents green juice cloud bread cardigan taiyaki adaptogen. Butcher hell of organic trust fund, adaptogen lo-fi ennui. Health goth +1 actually, vexillologist wolf banh mi before they sold out taxidermy twee intelligentsia. Celiac truffaut master cleanse small batch disrupt tacos cardigan bushwick microdosing succulents you probably haven't heard of them sriracha portland church-key VHS.

                                Neutra hell of mixtape live-edge dreamcatcher cornhole helvetica. Freegan VHS organic tote bag, franzen affogato subway tile synth schlitz succulents pok pok kombucha iceland enamel pin umami. Beard forage pork belly synth kickstarter, street art kinfolk. Shabby chic keytar narwhal fixie jianbing poutine vice. Af vegan health goth street art letterpress cardigan, hella gluten-free copper mug man bun heirloom meditation dreamcatcher. Cornhole adaptogen ugh deep v franzen. Forage PBR&B before they sold out vaporware, locavore food truck hoodie neutra disrupt cronut. Fam tilde cray, ennui humblebrag meh marfa ethical meditation. Pinterest seitan master cleanse drinking vinegar fingerstache, hexagon cray PBR&B jianbing street art. Shabby chic 90's asymmetrical literally polaroid. PBR&B heirloom food truck kogi franzen. Organic hashtag pickled fixie semiotics vinyl stumptown tousled af cray subway tile sriracha intelligentsia actually master cleanse.

                                Lumbersexual vexillologist meggings neutra shabby chic schlitz bushwick four loko pickled pop-up. Street art retro copper mug raclette cloud bread drinking vinegar lomo pop-up health goth fashion axe art party. Shaman glossier vaporware thundercats jean shorts gochujang meh vice franzen bicycle rights tofu artisan tacos. Chicharrones vape hot chicken chartreuse cliche small batch. Enamel pin you probably haven't heard of them meh taiyaki pickled selfies meditation flexitarian. La croix pok pok cold-pressed, lo-fi tofu farm-to-table normcore deep v chillwave kitsch try-hard. Trust fund cardigan scenester, succulents jianbing XOXO lomo meh literally live-edge pabst typewriter. Echo park fam sriracha small batch live-edge venmo everyday carry drinking vinegar neutra biodiesel pitchfork 8-bit lyft kombucha. Actually art party stumptown coloring book raw denim narwhal.

                                Swag flannel 3 wolf moon.</p>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

const mapStateToProps = (state) => {
    return {
        headerState: state
    }
};

const mapDispatchToProps = (dispatch) => {
    return bindActionCreators({
        showModal,
        hideModal,
        resetNotification,
        disableError,

    }, dispatch);
};

export default connect(mapStateToProps, mapDispatchToProps)(Header);